.PHONY: help install up down backend frontend migrate migration seed seed-reset \
        test test-be test-fe test-e2e build docker logs clean

# Default target
help:
	@echo ""
	@echo "  Setup"
	@echo "    install        Install all dependencies (uv sync + pnpm install)"
	@echo ""
	@echo "  Database"
	@echo "    up             Start Postgres + pgAdmin (detached)"
	@echo "    down           Stop all containers"
	@echo "    migrate        Run pending Alembic migrations"
	@echo "    migration n=…  Create new autogenerated migration  (make migration n=\"add index\")"
	@echo ""
	@echo "  Dev servers      Run each in a separate terminal"
	@echo "    backend        Start FastAPI with hot-reload (port 8000)"
	@echo "    frontend       Start Vite dev server (port 5173)"
	@echo ""
	@echo "  Seed data"
	@echo "    seed           Upsert seed data (idempotent)"
	@echo "    seed-reset     Wipe seed rows then re-insert"
	@echo ""
	@echo "  Tests"
	@echo "    test           Run all tests (backend + frontend unit)"
	@echo "    test-be        Backend pytest"
	@echo "    test-fe        Frontend Vitest (unit)"
	@echo "    test-e2e       Frontend Playwright E2E (requires backend + seed)"
	@echo ""
	@echo "  Docker (full stack)"
	@echo "    build          Build all Docker images"
	@echo "    docker         Build and start full stack (ports 8000 + 5174)"
	@echo "    logs           Tail container logs"
	@echo ""
	@echo "  Misc"
	@echo "    clean          Remove __pycache__ and dist artifacts"
	@echo ""

# ─── Setup ────────────────────────────────────────────────────────────────────

install:
	cd backend && uv sync
	cd frontend && pnpm install

# ─── Database ─────────────────────────────────────────────────────────────────

up:
	docker compose up -d postgres pgadmin
	@echo "  Postgres:  localhost:5432"
	@echo "  pgAdmin:   http://localhost:5050"

down:
	docker compose down

migrate:
	cd backend && uv run alembic upgrade head

migration:
ifndef n
	$(error Usage: make migration n="description of change")
endif
	cd backend && uv run alembic revision --autogenerate -m "$(n)"

# ─── Dev servers ──────────────────────────────────────────────────────────────

backend:
	cd backend && uv run uvicorn src.main:app --reload --port 8000

frontend:
	cd frontend && pnpm dev

# ─── Seed data ────────────────────────────────────────────────────────────────

seed:
	cd backend && uv run python -m scripts.seed

seed-reset:
	cd backend && uv run python -m scripts.seed --reset

# ─── Tests ────────────────────────────────────────────────────────────────────

test: test-be test-fe

test-be:
	cd backend && uv run pytest

test-fe:
	cd frontend && pnpm test

test-e2e:
	cd frontend && pnpm test:e2e

# ─── Docker ───────────────────────────────────────────────────────────────────

build:
	docker compose build

docker:
	docker compose up --build

logs:
	docker compose logs -f backend frontend

# ─── Misc ─────────────────────────────────────────────────────────────────────

clean:
	find backend -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find backend -name "*.pyc" -delete 2>/dev/null || true
	rm -rf frontend/dist frontend/.vite
