"""add sprint goal field

Revision ID: 7013b7d457bf
Revises: 10acb523279a
Create Date: 2026-04-24 13:34:06.234904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7013b7d457bf'
down_revision: Union[str, Sequence[str], None] = '10acb523279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('goal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'goal')
    # ### end Alembic commands ###
